CREATE TABLE IF NOT EXISTS public.users (
  id uuid PRIMARY KEY,
  email text NOT NULL,
  password_hash text NOT NULL,
  name text NOT NULL,
  city text NOT NULL DEFAULT '',
  styles_json jsonb NOT NULL DEFAULT '[]'::jsonb,
  precise_location boolean NOT NULL DEFAULT false,
  created_at bigint NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS users_email_lower_unique ON public.users (lower(email));

CREATE TABLE IF NOT EXISTS public.sessions (
  token_hash text PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  expires_at bigint NOT NULL,
  created_at bigint NOT NULL
);
CREATE INDEX IF NOT EXISTS sessions_user_idx ON public.sessions(user_id);

CREATE TABLE IF NOT EXISTS public.images (
  id uuid PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  kind text NOT NULL,
  mime_type text NOT NULL,
  object_path text NOT NULL UNIQUE,
  created_at bigint NOT NULL
);
CREATE INDEX IF NOT EXISTS images_user_idx ON public.images(user_id);

CREATE TABLE IF NOT EXISTS public.wardrobe_items (
  id uuid PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  image_id uuid REFERENCES public.images(id) ON DELETE SET NULL,
  name text NOT NULL,
  category text NOT NULL,
  color text NOT NULL,
  pattern text NOT NULL DEFAULT '',
  material text NOT NULL DEFAULT '',
  formality text NOT NULL DEFAULT 'Casual',
  season text NOT NULL DEFAULT 'All seasons',
  notes text NOT NULL DEFAULT '',
  favorite boolean NOT NULL DEFAULT false,
  available boolean NOT NULL DEFAULT true,
  worn integer NOT NULL DEFAULT 0,
  added_at bigint NOT NULL
);
CREATE INDEX IF NOT EXISTS wardrobe_user_idx ON public.wardrobe_items(user_id, added_at DESC);

CREATE TABLE IF NOT EXISTS public.outfits (
  id uuid PRIMARY KEY,
  source_id text NOT NULL,
  user_id uuid NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  item_ids_json jsonb NOT NULL,
  title text NOT NULL,
  blurb text NOT NULL,
  why text NOT NULL,
  occasion_fit text NOT NULL,
  weather_fit text NOT NULL,
  styling_notes text NOT NULL,
  compromise_note text NOT NULL DEFAULT '',
  shopping_suggestion text NOT NULL DEFAULT '',
  worn boolean NOT NULL DEFAULT false,
  saved_at bigint NOT NULL
);
CREATE INDEX IF NOT EXISTS outfits_user_idx ON public.outfits(user_id, saved_at DESC);
CREATE UNIQUE INDEX IF NOT EXISTS outfits_user_source_unique ON public.outfits(user_id, source_id);

CREATE TABLE IF NOT EXISTS public.rate_events (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id text NOT NULL,
  action text NOT NULL,
  created_at bigint NOT NULL
);
CREATE INDEX IF NOT EXISTS rate_events_lookup_idx ON public.rate_events(user_id, action, created_at);

ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.images ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.wardrobe_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.outfits ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.rate_events ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON TABLE public.users, public.sessions, public.images, public.wardrobe_items, public.outfits, public.rate_events FROM anon, authenticated;
REVOKE ALL ON SEQUENCE public.rate_events_id_seq FROM anon, authenticated;
